# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSession.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 478)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.time = QtWidgets.QTimeEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(190, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.time.setFont(font)
        self.time.setStyleSheet("QTimeEdit{\n"
"    font: 75 12pt \"VAG World\";\n"
"    border-image: url(:/rectangles/Rectangle2.png);\n"
"}\n"
"QTimeEdit::up-button {\n"
"    image: url(:/cinema/up.png);\n"
"}\n"
"QTimeEdit::down-button{\n"
"    image: url(:/cinema/Bt_AngelDown.png);\n"
"}\n"
"")
        self.time.setObjectName("time")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 221, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.filmName = QtWidgets.QLineEdit(self.centralwidget)
        self.filmName.setGeometry(QtCore.QRect(230, 290, 161, 31))
        self.filmName.setStyleSheet("font: 75 12pt \"VAG World\";\n"
"border-image: url(:/rectangles/Rectangle2.png);")
        self.filmName.setObjectName("filmName")
        self.date = QtWidgets.QCalendarWidget(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(20, 0, 371, 221))
        self.date.setStyleSheet("#qt_calendar_nextmonth {\n"
"    icon-size: 20px;\n"
"    qproperty-icon: url(:/cinema/right.png);\n"
"}\n"
"#qt_calendar_prevmonth {\n"
"    icon-size: 20px;\n"
"    qproperty-icon: url(:/cinema/left.png);\n"
"}\n"
"QCalendarWidget QToolButton{\n"
"background-color: #800080;\n"
"color: white;\n"
"icon-size: 30px;\n"
"font: 75 12pt \"VAG World\";\n"
"}\n"
"QCalendarWidget QWidget{\n"
"background-color:#800080;\n"
"}\n"
"QCalendarWidget QAbstractItemView:enabled{\n"
"background-color: white;\n"
"}\n"
"")
        self.date.setObjectName("date")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(100, 390, 221, 23))
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setStyleSheet("border-image: url(:/cinema/Rectangle.png);\n"
"font: 75 12pt \"VAG World\";")
        self.next.setObjectName("next")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.duration = QtWidgets.QLineEdit(self.centralwidget)
        self.duration.setGeometry(QtCore.QRect(332, 339, 61, 31))
        self.duration.setStyleSheet("font: 75 12pt \"VAG World\";\n"
"border-image: url(:/rectangles/Rectangle2.png);")
        self.duration.setObjectName("duration")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Установите время"))
        self.label_3.setText(_translate("MainWindow", "Введите название фильма"))
        self.next.setText(_translate("MainWindow", "далее"))
        self.label_4.setText(_translate("MainWindow", "Введите продолжительность(в минутах)"))
