# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateSeats.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 314)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rowCount = QtWidgets.QSpinBox(self.centralwidget)
        self.rowCount.setGeometry(QtCore.QRect(330, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.rowCount.setFont(font)
        self.rowCount.setStyleSheet("QSpinBox::up-button {\n"
"    image: url(:/cinema/up.png);\n"
"}\n"
"QSpinBox::down-button{\n"
"    image: url(:/cinema/Bt_AngelDown.png);\n"
"}\n"
"QSpinBox{\n"
"    border-image: url(:/cinema/Rectangle6.png);\n"
"\n"
"}\n"
"\n"
"")
        self.rowCount.setMinimum(2)
        self.rowCount.setMaximum(20)
        self.rowCount.setObjectName("rowCount")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 21))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 301, 21))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setObjectName("label_2")
        self.seatCount = QtWidgets.QSpinBox(self.centralwidget)
        self.seatCount.setGeometry(QtCore.QRect(330, 60, 101, 22))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.seatCount.setFont(font)
        self.seatCount.setStyleSheet("QSpinBox::up-button {\n"
"    image: url(:/cinema/up.png);\n"
"}\n"
"QSpinBox::down-button{\n"
"    image: url(:/cinema/Bt_AngelDown.png);\n"
"}\n"
"QSpinBox{\n"
"    border-image: url(:/cinema/Rectangle6.png);\n"
"}\n"
"\n"
"")
        self.seatCount.setMinimum(2)
        self.seatCount.setMaximum(20)
        self.seatCount.setObjectName("seatCount")
        self.seatType = QtWidgets.QComboBox(self.centralwidget)
        self.seatType.setGeometry(QtCore.QRect(130, 100, 301, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.seatType.setFont(font)
        self.seatType.setStyleSheet("QComboBox QAbstractItemView{\n"
"    font: 75 12pt \"VAG World\";\n"
"}\n"
"\n"
"QComboBox{\n"
"    border-image: url(:/cinema/Rectangle6.png)\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/cinema/Bt_AngelDown.png);\n"
"    left: -7px;\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: none;\n"
"}\n"
"")
        self.seatType.setObjectName("seatType")
        self.seatType.addItem("")
        self.seatType.addItem("")
        self.seatType.addItem("")
        self.seatType.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 105, 91, 21))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(10, 180, 411, 51))
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setStyleSheet("border-image: url(:/cinema/Rectangle.png);\n"
"font: 75 12pt \"VAG World\";")
        self.next.setObjectName("next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Задать количество рядов:"))
        self.label_2.setText(_translate("MainWindow", "Задать количество мест (в одном ряду):"))
        self.seatType.setItemText(0, _translate("MainWindow", "Маленькие кресла"))
        self.seatType.setItemText(1, _translate("MainWindow", "Средние кресла"))
        self.seatType.setItemText(2, _translate("MainWindow", "Большие кресла"))
        self.seatType.setItemText(3, _translate("MainWindow", "Диваны"))
        self.label_3.setText(_translate("MainWindow", "Тип кресел:"))
        self.next.setText(_translate("MainWindow", "Далее"))

