# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(357, 410)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/rectangles/ticket.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 250, 201, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 290, 331, 31))
        self.scrollArea.setStyleSheet("border: none;\n"
"background-color: white;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 331, 31))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.seatList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.seatList.setEnabled(True)
        self.seatList.setGeometry(QtCore.QRect(20, 0, 301, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(13)
        self.seatList.setFont(font)
        self.seatList.setStyleSheet("QListWidget{\n"
"    border-image: url(:/cinema/Rectangle2.png);\n"
"}\n"
"QScrollBar:vertical {              \n"
"    border: none; \n"
"    background: white;\n"
"    width: 5px;               \n"
"    margin: 0px 0px 0px 0px;\n"
"    min-height: 0px;  \n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #00008b;\n"
"    min-height: 0px;\n"
"}\n"
"\n"
"\n"
"")
        self.seatList.setObjectName("seatList")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 340, 191, 16))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 340, 31, 16))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.hall = QtWidgets.QLineEdit(self.centralwidget)
        self.hall.setEnabled(False)
        self.hall.setGeometry(QtCore.QRect(310, 338, 31, 20))
        self.hall.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.hall.setObjectName("hall")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Ваши места"))
        self.label_2.setText(_translate("MainWindow", "Приятного просмотра!"))
        self.label_3.setText(_translate("MainWindow", "Зал"))
