# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1083)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFilm = QtWidgets.QComboBox(self.centralwidget)
        self.selectFilm.setGeometry(QtCore.QRect(440, 140, 281, 41))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.selectFilm.setFont(font)
        self.selectFilm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectFilm.setStyleSheet("QComboBox QAbstractItemView{\n"
                                      "    font: 75 12pt \"VAG World\";\n"
                                      "}\n"
                                      "\n"
                                      "QComboBox{\n"
                                      "    border-image: url(:/cinema/Rectangle6.png)\n"
                                      "}\n"
                                      "QComboBox::down-arrow{\n"
                                      "    image: url(:/cinema/Bt_AngelDown.png);\n"
                                      "    left: -7px;\n"
                                      "}\n"
                                      "QComboBox::drop-down{\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "")
        self.selectFilm.setObjectName("selectFilm")
        self.selectFilm.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 10, 1000, 961))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setStyleSheet("image: url(:/cinema/Screen.png);\n"
                                   "padding: -800px 0px 0px 0px;\n"
                                   "border-image: url(:/cinema/Rectangle8.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.selectTime = QtWidgets.QComboBox(self.centralwidget)
        self.selectTime.setGeometry(QtCore.QRect(440, 230, 281, 41))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.selectTime.setFont(font)
        self.selectTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectTime.setStyleSheet("QComboBox QAbstractItemView{\n"
                                      "    font: 75 12pt \"VAG World\";\n"
                                      "}\n"
                                      "\n"
                                      "QComboBox{\n"
                                      "    border-image: url(:/cinema/Rectangle6.png)\n"
                                      "}\n"
                                      "QComboBox::down-arrow{\n"
                                      "    image: url(:/cinema/Bt_AngelDown.png);\n"
                                      "    left: -7px;\n"
                                      "}\n"
                                      "QComboBox::drop-down{\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "")
        self.selectTime.setMaxVisibleItems(5)
        self.selectTime.setObjectName("selectTime")
        self.selectTime.addItem("")
        self.selectCinema = QtWidgets.QComboBox(self.centralwidget)
        self.selectCinema.setGeometry(QtCore.QRect(440, 50, 281, 41))
        self.selectCinema.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.selectCinema.setFont(font)
        self.selectCinema.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectCinema.setStyleSheet("QComboBox QAbstractItemView{\n"
                                        "    font: 75 12pt \"VAG World\";\n"
                                        "}\n"
                                        "\n"
                                        "QComboBox{\n"
                                        "    border-image: url(:/cinema/Rectangle6.png)\n"
                                        "}\n"
                                        "QComboBox::down-arrow{\n"
                                        "    image: url(:/cinema/Bt_AngelDown.png);\n"
                                        "    left: -7px;\n"
                                        "}\n"
                                        "QComboBox::drop-down{\n"
                                        "    border: none;\n"
                                        "}\n"
                                        "")
        self.selectCinema.setMaxVisibleItems(5)
        self.selectCinema.setObjectName("selectCinema")
        self.selectCinema.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 310, 591, 621))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(270, 90, 271, 31))
        self.scrollArea.setStyleSheet("border: none;\n"
                                      "background-color: white;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 271, 31))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.seatList = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.seatList.setGeometry(QtCore.QRect(10, 0, 256, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(13)
        self.seatList.setFont(font)
        self.seatList.setStyleSheet("QListWidget{\n"
                                    "    border-image: url(:/cinema/Rectangle2.png);\n"
                                    "}\n"
                                    "QScrollBar:vertical {              \n"
                                    "    border: none; \n"
                                    "    background: white;\n"
                                    "    width: 5px;               \n"
                                    "    margin: 0px 0px 0px 0px;\n"
                                    "    min-height: 0px;  \n"
                                    "}\n"
                                    "QScrollBar::handle:vertical {\n"
                                    "    background: #00008b;\n"
                                    "    min-height: 0px;\n"
                                    "}\n"
                                    "\n"
                                    "\n"
                                    "")
        self.seatList.setObjectName("seatList")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(420, 35, 61, 16))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.toPay = QtWidgets.QLineEdit(self.widget)
        self.toPay.setEnabled(False)
        self.toPay.setGeometry(QtCore.QRect(280, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.toPay.setFont(font)
        self.toPay.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.toPay.setObjectName("toPay")
        self.paySeats = QtWidgets.QPushButton(self.widget)
        self.paySeats.setGeometry(QtCore.QRect(180, 542, 231, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.paySeats.setFont(font)
        self.paySeats.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paySeats.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.paySeats.setObjectName("paySeats")
        self.payLabel = QtWidgets.QLabel(self.widget)
        self.payLabel.setGeometry(QtCore.QRect(100, 210, 400, 300))
        self.payLabel.setText("")
        self.payLabel.setObjectName("payLabel")
        self.date = QtWidgets.QCalendarWidget(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(30, 50, 371, 221))
        self.date.setStyleSheet("#qt_calendar_nextmonth {\n"
                                "    icon-size: 20px;\n"
                                "    qproperty-icon: url(:/cinema/right.png);\n"
                                "}\n"
                                "#qt_calendar_prevmonth {\n"
                                "    icon-size: 20px;\n"
                                "    qproperty-icon: url(:/cinema/left.png);\n"
                                "}\n"
                                "QCalendarWidget QToolButton{\n"
                                "background-color: #800080;\n"
                                "color: white;\n"
                                "icon-size: 30px;\n"
                                "font: 75 12pt \"VAG World\";\n"
                                "}\n"
                                "QCalendarWidget QWidget{\n"
                                "background-color:#800080;\n"
                                "}\n"
                                "QCalendarWidget QAbstractItemView:enabled{\n"
                                "background-color: white;\n"
                                "}\n"
                                "")
        self.date.setObjectName("date")
        self.pricesWidget = QtWidgets.QWidget(self.centralwidget)
        self.pricesWidget.setGeometry(QtCore.QRect(600, 340, 281, 311))
        self.pricesWidget.setObjectName("pricesWidget")
        self.pricelabel1 = QtWidgets.QPushButton(self.pricesWidget)
        self.pricelabel1.setGeometry(QtCore.QRect(10, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pricelabel1.setFont(font)
        self.pricelabel1.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pricelabel1.setText("")
        self.pricelabel1.setObjectName("pricelabel1")
        self.price1 = QtWidgets.QLineEdit(self.pricesWidget)
        self.price1.setEnabled(False)
        self.price1.setGeometry(QtCore.QRect(190, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.price1.setFont(font)
        self.price1.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.price1.setObjectName("price1")
        self.price2 = QtWidgets.QLineEdit(self.pricesWidget)
        self.price2.setEnabled(False)
        self.price2.setGeometry(QtCore.QRect(190, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.price2.setFont(font)
        self.price2.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.price2.setObjectName("price2")
        self.pricelabel2 = QtWidgets.QPushButton(self.pricesWidget)
        self.pricelabel2.setGeometry(QtCore.QRect(10, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pricelabel2.setFont(font)
        self.pricelabel2.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pricelabel2.setText("")
        self.pricelabel2.setObjectName("pricelabel2")
        self.price3 = QtWidgets.QLineEdit(self.pricesWidget)
        self.price3.setEnabled(False)
        self.price3.setGeometry(QtCore.QRect(190, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.price3.setFont(font)
        self.price3.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.price3.setObjectName("price3")
        self.pricelabel3 = QtWidgets.QPushButton(self.pricesWidget)
        self.pricelabel3.setGeometry(QtCore.QRect(10, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pricelabel3.setFont(font)
        self.pricelabel3.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pricelabel3.setText("")
        self.pricelabel3.setObjectName("pricelabel3")
        self.price4 = QtWidgets.QLineEdit(self.pricesWidget)
        self.price4.setEnabled(False)
        self.price4.setGeometry(QtCore.QRect(190, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.price4.setFont(font)
        self.price4.setStyleSheet("border-image: url(:/cinema/Rectangle2.png);")
        self.price4.setObjectName("price4")
        self.pricelabel4 = QtWidgets.QPushButton(self.pricesWidget)
        self.pricelabel4.setGeometry(QtCore.QRect(10, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.pricelabel4.setFont(font)
        self.pricelabel4.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.pricelabel4.setText("")
        self.pricelabel4.setObjectName("pricelabel4")
        self.label = QtWidgets.QLabel(self.pricesWidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(30, 10, 181, 23))
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("border-image: url(:/cinema/Rectangle.png);")
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFilm.setItemText(0, _translate("MainWindow", "Выберите фильм"))
        self.selectTime.setItemText(0, _translate("MainWindow", "Выберите время"))
        self.selectCinema.setItemText(0, _translate("MainWindow", "Выберите кинотеатр"))
        self.pushButton.setText(_translate("MainWindow", "Итого к оплате"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбранные места"))
        self.label_3.setText(_translate("MainWindow", "руб"))
        self.paySeats.setText(_translate("MainWindow", "Оплатить"))
        self.label.setText(_translate("MainWindow", "Цены на билеты:"))
        self.exit.setText(_translate("MainWindow", "Выйти"))
